# Generated by Django 2.2.8 on 2019-12-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sri', '0006_sritarifaice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SriTarifaIRBPNR',
            fields=[
                ('sri_tipo_impuesto_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('porcentaje_retencion', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
