# Generated by Django 2.2.8 on 2020-01-16 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadmedida', '0001_initial'),
        ('sri', '0009_sriformapago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_deducible', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=5,
                                                  default=0, help_text='Porcentaje descuento', max_digits=15)),
                ('ice', models.ForeignKey(blank=True, null=True,
                                          on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTarifaICE')),
                ('iva', models.ForeignKey(blank=True, null=True,
                                          on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTarifaIVA')),
                #('medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.UnidadMedida')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.UnidadMedida')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
        ),
    ]
