# Generated by Django 2.2.8 on 2019-12-25 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0007_sritarifairbpnr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_principal', models.CharField(max_length=30, unique=True)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25, null=True)),
                #('es_servicio', models.BooleanField(default=False)),
                ('es_deducible', models.BooleanField(default=False)),
                ('marca', models.CharField(blank=True, max_length=40, null=True)),
                ('modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('unidad_equivalencia', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Observaciones', null=True)),
                ('precio_costo', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_uno', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('descuento_uno', models.DecimalField(decimal_places=5,
                                                      default=0, help_text='Porcentaje', max_digits=15)),
                ('utilidad_uno', models.DecimalField(decimal_places=5,
                                                     default=0, help_text='Porcentaje', max_digits=15)),
                ('precio_neto_uno', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_dos', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('descuento_dos', models.DecimalField(decimal_places=5,
                                                      default=0, help_text='Porcentaje', max_digits=15)),
                ('utilidad_dos', models.DecimalField(decimal_places=5,
                                                     default=0, help_text='Porcentaje', max_digits=15)),
                ('precio_neto_dos', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_tres', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('descuento_tres', models.DecimalField(decimal_places=5,
                                                       default=0, help_text='Porcentaje', max_digits=15)),
                ('utilidad_tres', models.DecimalField(decimal_places=5,
                                                      default=0, help_text='Porcentaje', max_digits=15)),
                ('precio_neto_tres', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_cuatro', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('descuento_cuatro', models.DecimalField(decimal_places=5,
                                                         default=0, help_text='Porcentaje', max_digits=15)),
                ('utilidad_cuatro', models.DecimalField(decimal_places=5,
                                                        default=0, help_text='Porcentaje', max_digits=15)),
                ('precio_neto_cuatro', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_principal', models.PositiveSmallIntegerField(choices=[
                 (1, 'PRECIO 1'), (2, 'PRECIO 2'), (3, 'PRECIO 3'), (4, 'PRECIO 4')])),
                ('cantidad_minima', models.IntegerField(default=0)),
                ('cantidad_maxima', models.IntegerField(default=0)),
                ('cantidad_inicial', models.IntegerField(default=0)),
                ('tiene_vencimiento', models.BooleanField(default=False)),
                ('tiene_serie', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True,
                                           default='product-img/no-img.jpg', null=True, upload_to='product-img/')),
                ('metodo_costo', models.CharField(blank=True, choices=[('PEPS', 'PRIMERAS ENTRADAS, PRIMERAS SALIDAS'), (
                    'UEPS', 'ÚLTIMAS ENTRADAS, PRIMERAS SALIDAS'), ('PROM', 'PROMEDIO PONDERADO')], default='PROM', max_length=5, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.SET_NULL, to='producto.Categoria')),
                ('equivalente', models.ManyToManyField(blank=True,
                                                       related_name='_producto_equivalente_+', to='producto.Producto')),
                ('ice', models.ForeignKey(blank=True, null=True,
                                          on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTarifaICE')),
                ('irbpnr', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTarifaIRBPNR')),
                ('iva', models.ForeignKey(blank=True, null=True,
                                          on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTarifaIVA')),
                # ('unidad_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                #                                       related_name='unidad_principal', to='unidadmedida.UnidadMedida')),
                # ('unidad_principal', models.ForeignKey(default='UN', on_delete=django.db.models.deletion.CASCADE,
                #                                       related_name='unidad_principal', to='unidadmedida.UnidadMedida', to_field='abreviatura')),
                ('unidad_principal', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='unidad_principal', to='unidadmedida.UnidadMedida')),
                ('unidad_secundaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                        related_name='unidad_secundaria', to='unidadmedida.UnidadMedida')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
            options={
                'unique_together': {('codigo_principal', 'nombre')},
            },
        ),
    ]
