# Generated by Django 2.2.8 on 2019-12-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('componente_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('productos', models.ManyToManyField(to='producto.Producto')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
