# Generated by Django 2.2.8 on 2019-12-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_estadocheque_pagocheque'),
        ('administracion', '0004_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_origen', models.CharField(blank=True, max_length=16, null=True)),
                ('cta_destino', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_transf', models.DateField()),
                ('monto', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('banco_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='banco_destino', to='administracion.EntidadFinanciera')),
                ('banco_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='banco_origen', to='administracion.EntidadFinanciera')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='contabilidad.Pago')),
            ],
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[
                 ('TD', 'Tarjeta Débito'), ('TC', 'Tarjeta Crédito')], max_length=2)),
                ('tarjeta_nro', models.CharField(blank=True, max_length=16, null=True)),
                ('vaucher', models.CharField(blank=True, max_length=16, null=True)),
                ('monto', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='contabilidad.Pago')),
                ('tarjeta', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to='administracion.TarjetaBancaria')),
            ],
        ),

    ]
