# Generated by Django 2.2.8 on 2019-12-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_pagotransferencia_pagotarjeta'),
        ('administracion', '0004_secuencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('situacion', models.CharField(max_length=16, unique=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('valor_credito', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('plazo', models.IntegerField(default=0)),
                ('unidad_tiempo', models.CharField(choices=[
                 ('D', 'DÍAS'), ('M', 'MESES'), ('A', 'AÑOS')], max_length=1)),
                ('num_cuotas', models.IntegerField(default=0)),
                ('tasa_interes', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('cuota_nro', models.IntegerField(default=0)),
                ('vence', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_retenido', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('abono', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('estado', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.EstadoCredito')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='contabilidad.Pago')),
            ],
        ),
    ]
