# Generated by Django 2.2.8 on 2019-12-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_estadocredito_pagocredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=128)),
                ('clasificacion', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('PASIVO', 'PASIVO'), ('PATRIMONIO', 'PATRIMONIO'), (
                    'INGRESOS', 'INGRESOS'), ('GASTOS', 'GASTOS'), ('COSTOS', 'COSTOS'), ('DE ORDEN', 'DE ORDEN')], max_length=24)),
                ('tipo', models.CharField(choices=[('CLASE', 'CLASE'), ('GRUPO', 'GRUPO'), (
                    'CUENTA', 'CUENTA'), ('SUBCUENTA', 'SUBCUENTA'), ('AUXILIAR', 'AUXILIAR')], max_length=10)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contabilidad.PlanCuenta')),
                ('usuario_creador', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='plancuenta',
            constraint=models.UniqueConstraint(
                fields=('codigo', 'nombre', 'empresa'), name='cuenta_unica'),
        ),
    ]
