# Generated by Django 2.2.8 on 2019-12-26 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_asientocontable'),
        ('administracion', '0004_secuencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoAutomatico',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_enlace', models.CharField(max_length=32)),
                ('grupo_asiento', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=128)),
                ('debito', models.BooleanField(default=False)),
                ('credito', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.PlanCuenta')),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('usuario_creador', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='asientoautomatico',
            constraint=models.UniqueConstraint(
                fields=('codigo_enlace', 'empresa'), name='asiento_unico'),
        ),
    ]
