# Generated by Django 2.2.8 on 2019-12-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_asientoautomatico'),
    ]

    operations = [
        migrations.RunSQL("drop view if exists contabilidad_cuentaslibromayor;"),
        migrations.RunSQL("""
            create or replace view contabilidad_cuentaslibromayor as
            select debe.cuenta_id, cuenta.nombre, asiento.empresa_id
            from contabilidad_asientodebedetalle debe
            inner join contabilidad_asientocontable asiento on debe.asiento_id = asiento.id
            inner join contabilidad_plancuenta cuenta on debe.cuenta_id = cuenta.id
            group by asiento.empresa_id, cuenta.nombre, debe.cuenta_id
            union
            select haber.cuenta_id, cuenta.nombre, asiento.empresa_id
            from contabilidad_asientohaberdetalle haber
            inner join contabilidad_asientocontable asiento on haber.asiento_id = asiento.id
            inner join contabilidad_plancuenta cuenta on haber.cuenta_id = cuenta.id
            group by asiento.empresa_id, cuenta.nombre, haber.cuenta_id
            order by cuenta_id;
        """),
    ]
