# Generated by Django 2.2.8 on 2019-12-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_cuentaslibrodiario_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasLibroMayor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contabilidad_cuentaslibromayor',
                'managed': False,
            },
        ),
    ]
