# Generated by Django 2.2.8 on 2019-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_cuentaslibromayor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasLibroDiario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'contabilidad_cuentaslibrodiario',
                'managed': False,
            },
        ),
    ]
