# Generated by Django 2.2.8 on 2019-12-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_cuentaslibrodiario'),
    ]

    operations = [
        migrations.RunSQL("drop view if exists contabilidad_balancecomprobacion;"),
        migrations.RunSQL("""
            create or replace view contabilidad_balancecomprobacion as
            WITH tbl as
            (
            select lm.cuenta_id, lm.nombre, case when ld.tipo_movimiento = 'D' then ld.monto else 0 end as debe, case when ld.tipo_movimiento = 'H' then ld.monto else 0 end as haber, lm.empresa_id
            from contabilidad_cuentaslibromayor lm
            inner join contabilidad_cuentaslibrodiario ld on lm.cuenta_id = ld.cuenta_id
            )
            select row_number() OVER () as id, cuenta_id, nombre,
            case when sum(debe - haber) >= 0 then sum(debe - haber) else 0 end as saldo_deudor,
            case when sum(debe - haber) < 0 then sum(debe - haber) * -1 else 0 end as saldo_acreedor,
            empresa_id
            from tbl
            group by cuenta_id, nombre, empresa_id
            order by cuenta_id;
        """),
    ]
