# Generated by Django 2.2.8 on 2020-01-17 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sri', '0009_sriformapago'),
        ('proveedor', '0004_proveedorresumen'),
        ('compra', '0003_ordencompraretencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0004_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteRetencion',
            fields=[
                ('comprobante_retencion_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateTimeField(null=True)),
                ('numero_secuencia', models.IntegerField(default=0)),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.SmallIntegerField(null=True)),
                ('anio', models.SmallIntegerField(null=True)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('fecha_generado', models.DateTimeField(auto_now=True)),
                ('archivo_generado', models.TextField(blank=True, null=True)),
                ('archivo_autorizado', models.TextField(blank=True, null=True)),
                ('fecha_error', models.DateTimeField(blank=True, null=True)),
                ('archivo_error', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='compra.OrdenCompra')),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RetencionEstado',
            fields=[
                ('retencion_estado_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteRetencionDetalle',
            fields=[
                ('comprobante_retencion_detalle_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fecha_emision_documento_modificado', models.DateField(blank=True, null=True)),
                ('numero_documento_modificado', models.CharField(max_length=49)),
                #('tipo_impuesto', models.IntegerField(default=0)),
                ('tipo_impuesto', models.PositiveSmallIntegerField(
                    choices=[(1, 'RENTA'), (2, 'IVA')])),
                ('valor_base_imponible', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('retencion', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='retencion.ComprobanteRetencion')),
                ('sri_tipo_comprobante_modificado', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sri.SriTipoComprobante')),
                ('sri_tipo_impuesto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sri.SriTipoImpuesto')),
            ],
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='estado',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retencion.RetencionEstado'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='proveedor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='secuencia',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Secuencia'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='sri_tipo_comprobante',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoComprobante'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='sri_tipo_moneda',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoMoneda'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
