# Generated by Django 2.2.8 on 2020-01-17 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0004_secuencia'),
        ('producto', '0003_componente'),
        ('cliente', '0004_clienteresumen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sri', '0009_sriformapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('nota_credito_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sri_tipo_comprobante_modificado', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateTimeField(null=True)),
                ('numero_secuencia', models.IntegerField(default=0)),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_emision_documento_modificado', models.DateTimeField(blank=True, null=True)),
                ('numero_documento_modificado', models.CharField(max_length=49)),
                ('motivo_modificacion', models.TextField(blank=True, null=True)),
                ('valor_descuento', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_sin_impuesto', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_12', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_0', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_no_objeto_iva', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_exento', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_base_imponible_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_ice', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('fecha_generado', models.DateTimeField(auto_now=True)),
                ('archivo_generado', models.TextField(blank=True, null=True)),
                ('archivo_autorizado', models.TextField(blank=True, null=True)),
                ('fecha_error', models.DateTimeField(blank=True, null=True)),
                ('archivo_error', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoEstado',
            fields=[
                ('notacredito_estado_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notacredito',
            name='estado',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notacredito.NotaCreditoEstado'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='secuencia',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Secuencia'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='sri_tipo_comprobante',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoComprobante'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='sri_tipo_moneda',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoMoneda'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
