# Generated by Django 2.2.8 on 2019-12-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notacredito', '0001_initial'),
        ('producto', '0003_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('nota_credito_detalle_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_descuento', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_sin_impuesto', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_12', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_0', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_no_objeto_iva', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_exento', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_base_imponible_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_ice', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('nota_credito', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='notacredito.NotaCredito')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
