# Generated by Django 2.2.8 on 2019-12-25 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0003_tarjetabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('secuencia_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('punto_establecimiento', models.CharField(max_length=3)),
                ('punto_emision', models.CharField(max_length=3)),
                ('ultima_secuencia', models.IntegerField(default=0)),
                ('direccion_establecimiento', models.TextField(blank=True, null=True)),
                ('comprobante_total_filas', models.IntegerField(
                    default=0, help_text='Filas por comprobante')),
                ('comprobante_fisico_ancho', models.IntegerField(default=0)),
                ('comprobante_fisico_alto', models.IntegerField(default=0)),
                ('comprobante_fisico_margen_superior', models.IntegerField(default=0)),
                ('comprobante_fisico_margen_inferior', models.IntegerField(default=0)),
                ('comprobante_fisico_total_copias', models.IntegerField(
                    default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('comprobante_fisico_tipo_impresora', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Impresoras de tickets (POS) Matricial'), (
                    2, 'Impresoras de tickets (POS) Térmica'), (3, 'Impresora de Matriz de Puntos'), (4, 'Impresora de chorro de tinta'), (5, 'Impresora Láser')], null=True)),
                ('comprobante_fisico_tipo_protocolo', models.PositiveSmallIntegerField(
                    blank=True, choices=[(1, 'Ethernet'), (2, 'Wi-Fi'), (3, 'USB')], null=True)),
                ('comprobante_fisico_nombre_impresora', models.CharField(
                    blank=True, help_text='IP, nombre impresora', max_length=64, null=True)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('sri_tipo_comprobante', models.ForeignKey(blank=True, null=True,
                                                           on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoComprobante')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
