# Generated by Django 2.2.8 on 2019-12-26 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('tipo_movimiento_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('pide_referencia', models.BooleanField(default=False)),
                ('es_entrada', models.BooleanField(default=False)),
                ('es_salida', models.BooleanField(default=False)),
                ('es_existencia', models.BooleanField(default=False)),
                ('es_ajuste', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
