# Generated by Django 2.2.8 on 2020-01-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmedida', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0003_componente'),
        ('administracion', '0004_secuencia'),
        ('almacen', '0002_tipomovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('kardex_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orden_id', models.IntegerField(default=0, help_text='factura_id, orden_id, etc..')),
                ('numero_comprobante', models.CharField(blank=True, max_length=17, null=True)),
                ('referencia', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('costo', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('cantidad_total', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('precio_total', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('almacen', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to='almacen.Almacen')),
                ('empresa', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to='administracion.Empresa')),
                ('movimiento', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL, to='almacen.TipoMovimiento')),
                ('producto', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, to='producto.Producto')),
                ('unidad', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.UnidadMedida')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
