# Generated by Django 2.2.8 on 2020-01-17 00:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_componente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0003_kardex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProducto',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stock', models.DecimalField(decimal_places=8, default=0, max_digits=25)),
                ('precio', models.DecimalField(decimal_places=8, default=0, max_digits=25)),
                ('almacen', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='producto.Producto')),
            ],
            options={
                'unique_together': {('producto', 'almacen')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalControlProducto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stock', models.DecimalField(decimal_places=8, default=0, max_digits=25)),
                ('precio', models.DecimalField(decimal_places=8, default=0, max_digits=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacen', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.Almacen')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producto.Producto')),
            ],
            options={
                'verbose_name': 'historical control producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
