# Generated by Django 2.2.8 on 2020-01-17 01:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0003_componente'),
        ('almacen', '0004_controlproducto_historicalcontrolproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSerie',
            fields=[
                ('producto_serie_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('literal', models.IntegerField(default=1, help_text='Item: 1, 2, 3, etc.')),
                ('serie_numero', models.CharField(max_length=16, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('almacen', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                ('kardex', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to='almacen.Kardex')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLote',
            fields=[
                ('producto_lote_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                #('lote_numero', models.CharField(max_length=10, unique=True)),
                ('lote_numero', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True,
                                                help_text='Compra, Inventario Inicial, etc.', max_length=64, null=True)),
                ('fecha_caducidad', models.DateField(default=datetime.date.today)),
                #('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                # ('almacen', models.ForeignKey(
                #    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                # ('kardex', models.ForeignKey(blank=True, null=True,
                #                             on_delete=django.db.models.deletion.CASCADE, to='almacen.Kardex')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                ('kardex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.Kardex')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalControlProductoSerie',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacen', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.Almacen')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producto.Producto')),
                ('serie', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.ProductoSerie')),
            ],
            options={
                'verbose_name': 'historical control producto serie',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalControlProductoLote',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacen', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.Almacen')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.ProductoLote')),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producto.Producto')),
                #('kardex', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'historical control producto lote',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='productolote',
            constraint=models.UniqueConstraint(
                fields=('producto', 'lote_numero', 'fecha_caducidad'), name='unique_productolote'),
        ),
        migrations.CreateModel(
            name='ControlProductoSerie',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('almacen', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('serie', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.ProductoSerie')),
            ],
            options={
                'unique_together': {('almacen', 'producto', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='ControlProductoLote',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('almacen', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.Almacen')),
                ('lote', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='almacen.ProductoLote')),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
            options={
                'unique_together': {('almacen', 'producto', 'lote')},
            },
        ),
    ]
