# Generated by Django 2.2.8 on 2019-12-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_movimiento_query'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS almacen_productoresumen;"),
        migrations.RunSQL("""
            CREATE OR REPLACE VIEW almacen_productoresumen AS
            SELECT prod.producto_id,
                prod.nombre,
                prod.codigo_principal,
                prod_saldo.cantidad AS existencia,
                und.abreviatura AS unidad,
                prod.precio_costo,
                prod.precio_neto_uno,
                prod.precio_neto_dos,
                prod.precio_neto_tres,
                prod.precio_neto_cuatro
            FROM producto_producto prod
            LEFT JOIN unidadmedida_unidadmedida und ON und.unidad_medida_id = prod.unidad_principal_id
            LEFT JOIN almacen_movimientosaldo prod_saldo ON prod_saldo.producto_id = prod.producto_id
            ORDER BY prod.nombre;
        """),
    ]
