# Generated by Django 2.2.8 on 2019-12-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_productoresumen'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS almacen_inventarioexistencia;"),
        migrations.RunSQL("""
            CREATE VIEW almacen_inventarioexistencia AS
            SELECT prod.producto_id, prod.nombre, prod.codigo_principal,
                mov_saldo.cantidad AS existencia,
                und.abreviatura AS unidad,
                prod.cantidad_maxima
            FROM producto_producto prod
            LEFT JOIN unidadmedida_unidadmedida und ON und.unidad_medida_id = prod.unidad_principal_id
            LEFT JOIN almacen_movimientosaldo mov_saldo ON mov_saldo.producto_id = prod.producto_id;
        """),
    ]
