# Generated by Django 2.2.8 on 2019-12-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_inventarioexistencia_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioExistencia',
            fields=[
                ('producto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('codigo_principal', models.CharField(max_length=30, unique=True)),
                ('existencia', models.DecimalField(decimal_places=5, max_digits=15)),
                ('unidad', models.CharField(max_length=5)),
                ('cantidad_maxima', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'almacen_inventarioexistencia',
                'managed': False,
            },
        ),
    ]
