# Generated by Django 2.2.8 on 2019-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_productosaldo_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSaldo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'db_table': 'almacen_productosaldo',
                'managed': False,
            },
        ),
    ]
