# Generated by Django 2.2.8 on 2019-12-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_productoconsolidado_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoConsolidado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entradas', models.DecimalField(decimal_places=5, max_digits=15)),
                ('salidas', models.DecimalField(decimal_places=5, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'db_table': 'almacen_productoconsolidado',
                'managed': False,
            },
        ),
    ]
