# Generated by Django 2.2.8 on 2020-01-17 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_componente'),
        ('servicio', '0001_initial'),
        ('administracion', '0004_secuencia'),
        ('cliente', '0004_clienteresumen'),
        ('sri', '0009_sriformapago'),
        ('unidadmedida', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('nota_entrega_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateTimeField(null=True)),
                ('numero_secuencia', models.IntegerField(default=0)),
                ('valor_descuento', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_sin_impuesto', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_12', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_0', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_no_objeto_iva', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_exento', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_base_imponible_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_ice', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NotaEntregaEstado',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('situacion', models.CharField(max_length=16, unique=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='estado',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notaentrega.NotaEntregaEstado'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='secuencia',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Secuencia'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='sri_tipo_comprobante',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoComprobante'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
