# Generated by Django 2.2.8 on 2019-12-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notaentrega', '0001_initial'),
        ('producto', '0003_componente'),
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntregaDetalle',
            fields=[
                ('nota_entrega_detalle_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('precio_venta', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=5,
                                                             default=0, help_text='Porcentaje de descuento', max_digits=15)),
                ('valor_descuento', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_sin_impuesto', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_12', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_0', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_no_objeto_iva', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_exento', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_base_imponible_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_ice', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[
                 ('P', 'PRODUCTO'), ('S', 'SERVICIO')], max_length=1)),
                ('nota_entrega', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='notaentrega.NotaEntrega')),
                ('producto', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, to='producto.Producto')),
                ('servicio', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, to='servicio.Servicio')),
                ('unidad', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.UnidadMedida')),
            ],
        ),
    ]
