# Generated by Django 2.2.8 on 2020-01-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('unidad_medida_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TIEMPO', 'UNIDADES DE TIEMPO'), ('LONGITUD', 'UNIDADES DE LONGITUD'), (
                    'MASA', 'UNIDADES DE MASA'), ('VOLUMEN', 'UNIDADES DE VOLUMEN'), ('OTRAS', 'OTRAS UNIDADES')], default='OTRAS', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('abreviatura', models.CharField(max_length=5, unique=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
            ],
            options={
                'verbose_name_plural': 'unidades de medida',
            },
        ),
    ]
