# Generated by Django 2.2.8 on 2019-12-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS proveedor_proveedorsaldo;"),
        migrations.RunSQL("""
            create view proveedor_proveedorsaldo as
            select proveedor_id, 0 as saldo
            from proveedor_proveedor
        """),
    ]
