# Generated by Django 2.2.8 on 2019-12-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedorsaldo_query'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS proveedor_proveedorresumen;"),
        migrations.RunSQL("""
            create view proveedor_proveedorresumen as
            select prov.proveedor_id, prov.nombre, prov.identificacion, prov.direccion, prov.activo, prov_saldo.saldo
            from proveedor_proveedor prov
            inner join proveedor_proveedorsaldo prov_saldo on prov_saldo.proveedor_id = prov.proveedor_id
            order by prov.proveedor_id
        """),
    ]
