# Generated by Django 2.2.8 on 2020-01-16 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0004_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('papel', models.CharField(choices=[('VISITOR', 'Visitante'), ('EMPLOYEE', 'Empleado'), (
                    'ACCOUNTANT', 'Contador'), ('SUPERVISOR', 'Supervisor')], default='VISITOR', max_length=10)),
                ('foto', models.ImageField(blank=True, default='avatars/user.png',
                                           null=True, upload_to='avatars/', verbose_name='Foto de perfil')),
                ('usuario', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
