"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#wps%c-l8fwo)7h6eq8e!tsl*0_8-n8j9lxpelx&u(fheox8_4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'widget_tweaks',
    'crispy_forms',
    'simple_history',
    'mptt',
    'django.contrib.humanize',
    'mathfilters',
    'apps.dashboard',
    'apps.sri',
    'apps.administracion',
    'apps.usuario',
    'apps.unidadmedida',
    'apps.proveedor',
    'apps.cliente',
    'apps.almacen',
    'apps.producto',
    'apps.servicio',
    'apps.cesta',
    'apps.contabilidad',
    'apps.retencion',
    'apps.compra',
    'apps.venta',
    'apps.notaentrega',
    'apps.proforma',
    'apps.notadebito',
    'apps.notacredito',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    # Django templates for apps
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },

    # Jinja for our templates
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': ['%s/jinjatemplates/' % (PROJECT_DIR), ],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates/jinjatemplates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'app.jinja2.environment',
            'auto_reload': DEBUG,
            'autoescape': True,
            'extensions': [
                # 'jinja2.ext.i18n',
                # 'jinja2.ext.with_',
                # 'jinja2.ext.autoescape',
                # 'jdj_tags.extensions.DjangoStatic',
                # 'jdj_tags.extensions.DjangoI18n',
                # 'app.jinja.mis_extensiones.my_custom_tag',
            ]
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'facturae_prod',
        #'NAME': 'farmacia_gabrielito',
        'USER': 'userdb',
        'PASSWORD': 'i2+4LH24c{s]',
        'HOST': 'localhost',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-EC'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

USE_TZ = True

DEFAULT_USER_TIME_ZONE = 'America/Guayaquil'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_URL = 'http://localhost:9966/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, '../staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '../mediafiles')

# CORREO ELECTRÓNICO POR GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'infojavo@gmail.com'
EMAIL_HOST_PASSWORD = 'Broka2016'

# GOOGLE CAPTCHA
GOOGLE_RECAPTCHA_SECRET_KEY = '6Lfsq-IUAAAAAKZby6ddAo-_Dj1rGTsq2LYwMtmy'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'
