# Generated by Django 2.2.8 on 2020-01-16 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sri', '0009_sriformapago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, null=True, max_length=255)),
                ('telefono', models.CharField(blank=True, null=True, max_length=25)),
                ('celular', models.CharField(blank=True, null=True, max_length=25)),
                ('email', models.CharField(blank=True, null=True, max_length=100)),
                ('identificacion_tipo', models.ForeignKey(blank=True, null=True,
                                                          on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoIdentificacion')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
