# Generated by Django 2.2.8 on 2019-12-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clientesaldo_query'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS cliente_clienteresumen;"),
        migrations.RunSQL("""
        create view cliente_clienteresumen as
        select clte.cliente_id, clte.nombre, clte.identificacion, clte.direccion, clte.activo, clte_saldo.saldo
        from cliente_cliente clte
        inner join cliente_clientesaldo clte_saldo on clte_saldo.cliente_id = clte.cliente_id
        order by clte.cliente_id
        """),
    ]
