# Generated by Django 2.2.8 on 2019-12-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_clienteresumen_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteResumen',
            fields=[
                ('cliente_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('saldo', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'cliente_clienteresumen',
                'managed': False,
            },
        ),
    ]
