# Generated by Django 2.2.8 on 2019-12-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_ordencompradetalle'),
        ('sri', '0009_sriformapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraRetencion',
            fields=[
                ('orden_retencion_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.OrdenCompra')),
                ('sri_tipo_impuesto', models.ForeignKey(blank=True, null=True,
                                                        on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoImpuesto')),
            ],
            options={
                'verbose_name_plural': 'Orden Retenciones',
            },
        ),
    ]
