# Generated by Django 2.2.8 on 2019-12-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_facturadetalle_facturadetalleadicional'),
        ('sri', '0009_sriformapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaRetencion',
            fields=[
                ('factura_retencion_id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Factura')),
                ('sri_tipo_impuesto', models.ForeignKey(blank=True, null=True,
                                                        on_delete=django.db.models.deletion.SET_NULL, to='sri.SriTipoImpuesto')),
            ],
            options={
                'verbose_name_plural': 'Factura Retenciones',
            },
        ),
    ]
