# Generated by Django 2.2.8 on 2020-01-23 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_componente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicio', '0001_initial'),
        ('unidadmedida', '0001_initial'),
        ('administracion', '0004_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[
                 ('PROD', 'Producto'), ('SERV', 'Servicio')], default='PROD', max_length=4)),
                #('cantidad', models.IntegerField(default=1)),
                ('cantidad', models.DecimalField(decimal_places=5, default=1, max_digits=15)),
                # ('cantidad_aux', models.DecimalField(decimal_places=5,
                #                                     default=0, help_text='Auxiliar ajustes', max_digits=15)),

                ('precio', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=5,
                                                             default=0, help_text='Porcentaje de descuento', max_digits=15)),
                ('valor_descuento', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_sin_impuesto', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_12', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_0', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_no_objeto_iva', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_exento', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_base_imponible_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_subtotal_ibrpnr', models.DecimalField(
                    decimal_places=5, default=0, max_digits=15)),
                ('valor_ice', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('producto', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, to='producto.Producto')),
                ('servicio', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, to='servicio.Servicio')),
                #('unidad_medida_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_producto', to='unidadmedida.UnidadMedida')),
                #('unidad_medida_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_servicio', to='unidadmedida.UnidadMedida')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.UnidadMedida')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                #('serie_numero', models.CharField(max_length=16, unique=True)),
                ('serie_numero', models.CharField(max_length=16)),
                ('cantidad', models.DecimalField(decimal_places=5, default=1, max_digits=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesta.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                #('lote_numero', models.CharField(max_length=10, unique=True)),
                ('lote_numero', models.CharField(max_length=10)),
                ('fecha_caducidad', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.DecimalField(decimal_places=5, default=0, max_digits=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesta.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=datetime.datetime.now)),
                ('clave_apli', models.CharField(
                    help_text='CART-VENTA, CART-COMPRA, CART-PROFORMA, etc.', max_length=16)),
                #('clave_pers', models.CharField(help_text='RUC del Cliente o Proveedor', max_length=16)),
                ('items', models.ManyToManyField(to='cesta.Item')),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresa')),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
