# Generated by Django 2.2.8 on 2020-02-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('valor', models.CharField(max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='opciones', to='cesta.Item')),
            ],
        ),
    ]
